# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fe4995d52c1ffe9334ecc27e61540de42307927bc2dd0be28a0500d6a7feb0670b898c15e2fd59e197169f531b30c56449b916586b5fba2a650a2ef918fc967

test:
  secret_key_base: 40c376b549e7c10d881923b9b22beaf46255fd76b7db2ae53f96c17a0e401ee18397795c1a5ac5dccf41ae82cb868c06aa6e7df70dd2f3c3e56d2a27f101f7f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
